insert into EVENTS (EVENTCODE, TITLE, DESCRIPTION)
values('ABC123','Project Event','Example Description');

insert into REGISTRATION (CUSTOMER_ID, EVENT_ID, REGISTRATION_DATE, NOTES) VALUES('1', '1', 'today', 'none');
insert into REGISTRATION (CUSTOMER_ID, EVENT_ID, REGISTRATION_DATE, NOTES) VALUES(2, 4, 'tomorrow', 'negative');
insert into REGISTRATION (CUSTOMER_ID, EVENT_ID, REGISTRATION_DATE, NOTES) VALUES(5, 1, '2004', 'nada');
insert into REGISTRATION (CUSTOMER_ID, EVENT_ID, REGISTRATION_DATE, NOTES) VALUES(3, 2, '1776', 'nope');
insert into REGISTRATION (CUSTOMER_ID, EVENT_ID, REGISTRATION_DATE, NOTES) VALUES(2, 7, 'next week monday', 'nuh uh');