

-- ----------------------------------------------
-- DDL Statements for tables
-- ----------------------------------------------

CREATE TABLE "EVENTS" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "EVENTCODE" VARCHAR(255), "TITLE" VARCHAR(255), "DESCRIPTION" VARCHAR(255));

CREATE TABLE "REGISTRATION" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "CUSTOMER_ID" VARCHAR(255), "EVENT_ID" VARCHAR(255), "REGISTRATION_DATE" VARCHAR(255), "NOTES" VARCHAR(255));

CREATE TABLE "CUSTOMERS" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(255), "EMAIL" VARCHAR(255), "PASSWORD" VARCHAR(255));

--CREATE TABLE "GAMESUMMARY" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "CLIENTGESTURE" VARCHAR(255), "SERVERGESTURE" VARCHAR(255), "RESULT" VARCHAR(255), "TIMEPLAYED" TIMESTAMP);

--CREATE TABLE "GAMESUMMARY" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "CLIENTGESTURE" VARCHAR(255), "SERVERGESTURE" VARCHAR(255), "RESULT" VARCHAR(255), "TIMEPLAYED" TIMESTAMP);

-- ----------------------------------------------
-- DDL Statements for keys
-- ----------------------------------------------

-- primary/unique
ALTER TABLE "EVENTS" ADD CONSTRAINT "SQL120325130144010" PRIMARY KEY ("ID");

ALTER TABLE "REGISTRATION" ADD CONSTRAINT "SQL120325130144011" PRIMARY KEY ("ID");

ALTER TABLE "CUSTOMERS" ADD CONSTRAINT "SQL120325130144012" PRIMARY KEY ("ID");