FROM eclipse-temurin:17-jdk-alpine
COPY your-customers.jar app.jar
EXPOSE 8012
ENTRYPOINT ["java", "-jar", "app.jar"]

                                                                                   
                                                 
